/* ===========================================================
   KP Packaging, Site Data
   Single source of truth for products, industries, capabilities.
   =========================================================== */

const COMPANY = {
  name: "KP Packaging",
  legal: "KP Packaging",
  tagline: "Coated paper & flexible packaging, perfected over three decades.",
  stats: [
    { value: "30+", label: "Years of expertise" },
    { value: "25+", label: "Countries served" },
    { value: "500+", label: "Clients worldwide" }
  ],
  clients: [
    // colour-coordinated order: blues, purple, multicolour, reds
    { name: "Cipla", logo: "/assets/logos/cipla.webp" },
    { name: "Parksons", logo: "/assets/logos/parksons.webp" },
    { name: "Reliance Polymers", logo: "/assets/logos/reliance.webp" },
    { name: "Dr. Reddy's", logo: "/assets/logos/dr-reddys.webp" },
    { name: "Godrej", logo: "/assets/logos/godrej.webp" },
    { name: "Wipro", logo: "/assets/logos/wipro.webp" },
    { name: "Zydus", logo: "/assets/logos/zydus.webp" },
    { name: "Amul", logo: "/assets/logos/amul.webp" },
    { name: "Intas", logo: "/assets/logos/intas.webp" },
    { name: "Dow Chemicals", logo: "/assets/logos/dow.webp" },
    { name: "Wockhardt", logo: "/assets/logos/wockhardt.webp" }
  ],
  certs: [
    { name: "ISO Certified", logo: "/assets/certs/iso.webp" },
    { name: "AEO Indian Customs", logo: "/assets/certs/custom.webp" },
    { name: "Make in India", logo: "/assets/certs/make-in-india.webp" },
    { name: "MSME", logo: "/assets/certs/msme.webp" },
    { name: "CE", logo: "/assets/certs/ce.webp" },
    { name: "IAF", logo: "/assets/certs/iaf.webp" }
  ],
  team: [
    { name: "Madhukant Vira", role: "Chairman", photo: "/assets/team/3.webp" },
    { name: "Ketan Vira", role: "CEO", photo: "/assets/team/2.webp" },
    { name: "Prem Vira", role: "Director", photo: "/assets/team/1.webp" }
  ],
  offices: [
    {
      tag: "Corporate Office",
      city: "Mumbai",
      address: "A to Z Industrial Estate, Western Wing, Office No 143, Ganpat Rao Kadam Marg, Lower Parel, Mumbai, 400013",
      street: "A to Z Industrial Estate, Western Wing, Office No 143, Ganpat Rao Kadam Marg, Lower Parel",
      locality: "Mumbai", region: "Maharashtra", postal: "400013", country: "IN",
      phone: "+91 85916 56966",
      phoneRaw: "+918591656966",
      email: "prem@kppackaging.com"
    },
    {
      tag: "Manufacturing Plant",
      city: "Silvassa",
      address: "792, Apple Insulated, Nr Crown Tapes, Vaibhav Laxmi, Silvassa, India, 396193",
      street: "792, Apple Insulated, Nr Crown Tapes, Vaibhav Laxmi",
      locality: "Silvassa", region: "Dadra and Nagar Haveli", postal: "396193", country: "IN",
      phone: "+91 85916 94328",
      phoneRaw: "+918591694328",
      email: "sales@kppackaging.com"
    }
  ],

  /* ---- GEO/AEO entity + answer content ---- */
  url: "https://kppackaging.com",
  founded: "1990",                 // "over 3 decades"; replace with exact year when confirmed
  logo: "/assets/kp-logo.png",
  ogImage: "/assets/og-cover.png",
  sameAs: [],                      // add official LinkedIn/Instagram/Facebook URLs when available
  summary: "KP Packaging is a Mumbai-based manufacturer and distributor of coated papers and flexible packaging with over 30 years of experience. The company runs extrusion coating and lamination machines from Korea, China and the United States of America at its plant in Silvassa, India, and supplies pharmaceutical, food & beverage, FMCG and medical or surgical packaging to around 500 clients across about 25 countries.",
  why: [
    { title: "Three decades of converting expertise", text: "Over 30 years in coated paper and flexible packaging, from a PVC leather-cloth pioneer to a modern primary-packaging house." },
    { title: "Manufacturing + distribution under one roof", text: "In-house extrusion-coated laminates plus authorized distribution for leading Indian paper mills, source coating, printing and substrate from a single partner." },
    { title: "State-of-the-art coating lines", text: "A modern extrusion lamination and coating plant in Silvassa with rotogravure printing and multiple slitting, sheeting and rewinding machines." },
    { title: "Trusted by industry leaders", text: "We supply to Wockhardt, Cipla, Dr. Reddy's, Godrej, Wipro, Zydus, Amul, Parksons and Intas across 25+ countries." },
    { title: "Pharma- and food-grade quality", text: "FSC- and FDA-aligned barrier papers for medicines, ORS sachets, blister packs, paper cups, food packaging and lots more." },
    { title: "Custom laminates, made to spec", text: "We engineer bespoke coated and laminated structures to your exact barrier, print and substrate requirements, with reliable lead times." }
  ],
  faq: [
    { q: "What does KP Packaging do?", a: "KP Packaging manufactures extrusion-coated paper laminates and distributes a wide range of mill-grade papers for primary and flexible packaging, serving the pharmaceutical, food & beverage, FMCG and medical or surgical industries." },
    { q: "Where is KP Packaging located?", a: "Its corporate office is in Lower Parel, Mumbai, Maharashtra, and its manufacturing plant is in Silvassa, Dadra and Nagar Haveli, India." },
    { q: "How do I request a quote from KP Packaging?", a: "Contact the corporate office at prem@kppackaging.com or +91 85916 56966, the plant at sales@kppackaging.com or +91 85916 94328, or use the inquiry form on kppackaging.com." },
    { q: "Is KP Packaging a manufacturer or a distributor?", a: "Both. KP Packaging manufactures extrusion-coated laminates in-house and is also an authorized distributor for multiple Indian paper mills." },
    { q: "Does KP Packaging export internationally?", a: "Yes. KP Packaging serves 500+ clients across more than 25 countries and is actively expanding its international business." },
    { q: "What papers does KP Packaging make?", a: "KP Packaging supplies both coated and uncoated papers: glassine, MG poster, chromo, cupstock, MG kraft, MF craft, 3-ply and 4-ply foil laminates, folding box board, duplex board, greaseproof, tissue, medical grade, Bactide and grid coated papers." },
    { q: "Is KP Packaging's paper food-safe and pharma-grade?", a: "Yes. It supplies FDA- and FSC-aligned glassine and barrier papers for pharmaceuticals and food-safe cupstock and greaseproof papers for food and beverage packaging." }
  ]
};

const CAPABILITIES = [
  {
    slug: "extrusion-coating",
    title: "Extrusion Coating & Lamination",
    icon: "layers",
    blurb: "Poly (LDPE) coating on printed and unprinted paper, board and aluminium foil.",
    detail: "Our three state-of-the-art extrusion lamination and coating machines, imported from Korea, China and the United States of America, apply LDPE and specialty polymer layers across a wide range of substrates to deliver moisture, grease and oxygen barriers for primary packaging."
  },
  {
    slug: "rotogravure-printing",
    title: "Rotogravure Printing",
    icon: "printer",
    blurb: "High-resolution 8-colour gravure printing for sharp, durable, on-brand packaging.",
    detail: "Our 8-colour rotogravure press delivers consistent, high-volume print quality on films, foils and papers, ideal for branded flexible packaging and pharmaceutical laminates."
  },
  {
    slug: "slitting-rewinding",
    title: "Slitting & Rewinding",
    icon: "scissors",
    blurb: "Multiple slitting, sheeting and rewinding machines for precise reel widths to customer specifications.",
    detail: "Jumbo rolls are converted into precise, customer-specified reel widths and lengths, plain or printed, with tight tolerance and clean edges."
  },
  {
    slug: "paper-distribution",
    title: "Paper Distribution",
    icon: "truck",
    blurb: "Authorized distributor for leading Indian paper mills across a broad grade range.",
    detail: "Beyond manufacturing, we are authorized distributors for multiple Indian paper mills, supplying MG Poster, Maplitho, Cupstock, MG/MF Kraft, Greaseproof, Chromo, Glassine, Duplex, FBB, SBS and more."
  }
];

const INFRASTRUCTURE = [
  { count: 3, name: "Extrusion lamination machines", origin: "Korean, Chinese & American" },
  { count: 1, name: "8-colour rotogravure printing machine", origin: "Indian" },
  { count: 3, name: "Slitting machines", origin: "Italian (Bimec)" },
  { count: 1, name: "Slitting machine", origin: "German" },
  { count: 2, name: "Slitting machines", origin: "Indian" },
  { count: 1, name: "Sheet-cutting machine", origin: "Indian" }
];

const INDUSTRIES = [
  {
    slug: "pharmaceutical",
    name: "Pharmaceutical",
    art: "roll-art",
    image: "/assets/industries/pharmaceutical.webp",
    blurb: "Barrier papers and foil laminates for tablet strips, ORS sachets and blister packs.",
    detail: "We supply the barrier-grade papers and aluminium foil laminates that protect medicines from moisture, light and air, from glassine sachets to 4-ply foil laminates used by leading pharma brands. Our pharmaceutical-grade substrates safeguard tablet strips, ORS powders, blister and strip packs, condom laminates and surgical sutures, preserving potency and extending shelf life. With FDA- and FSC-aligned quality and consistent print and seal performance, we supply names such as Wockhardt, Cipla, Dr. Reddy's, Zydus and Intas.",
    products: ["glassine-paper", "4-ply-paper", "3-ply-paper", "folding-box-board", "medical-grade-paper", "non-tearable-paper"]
  },
  {
    slug: "food-beverage",
    name: "Food & Beverage",
    art: "roll-art--kraft",
    image: "/assets/industries/food-beverage.webp",
    blurb: "Food-safe, grease- and moisture-resistant papers for cups, wraps and pouches.",
    detail: "Food-contact-safe cupstock, greaseproof and MG poster papers engineered for hot & cold beverages, bakery, dairy and ready-to-eat packaging. PE, PLA and water-based coatings deliver dependable moisture, grease and heat resistance for paper cups, soup bowls, wrappers, trays, meal boxes and pouches. Every grade is produced to food-safe standards so it performs reliably from the production line all the way to the table.",
    products: ["cupstock-paper", "paper-lid", "liquid-packaging-board", "greaseproof-paper", "butter-packaging", "butcher-paper", "mg-poster-paper", "mg-kraft", "mf-craft-paper", "3-ply-paper", "anti-skid-paper"]
  },
  {
    slug: "fmcg",
    name: "FMCG & Retail",
    art: "roll-art--cream",
    image: "/assets/industries/fmcg.webp",
    blurb: "Printable, durable, coated papers and boards for everyday consumer solutions.",
    detail: "High-gloss, print-ready chromo and poster papers plus folding box board for retail packaging that needs shelf appeal and structural strength. From cartons and labels to sachets for tea, tobacco, gutka and personal-care products, our coated papers and boards pair sharp rotogravure printing with the stiffness and durability retail demands. We supply trusted FMCG names including Godrej, Wipro, Amul and Parksons.",
    products: ["chromo-paper", "mg-poster-paper", "folding-box-board", "duplex-board", "maplitho-paper", "mf-craft-paper", "anti-skid-paper"]
  },
  {
    slug: "medical-surgical",
    name: "Medical & Surgical",
    art: "roll-art",
    image: "/assets/industries/medical-surgical.webp",
    blurb: "ETO sterilization, bacterial barrier papers for gloves, syringes and surgical disposables.",
    detail: "Steam-sterilizable Bactide, medical grade and grid coated papers with bacterial-barrier and heat-sealing properties for medical gloves, syringes, catheters and surgical sutures. Free from optical brighteners and engineered for steam, EtO and gamma sterilization, these medical-grade papers hold a dependable bacterial barrier and a clean peel for surgical disposables. They are lint-free, fluid-repellent and high in dry and wet strength, trusted across hospital and device supply chains.",
    products: ["bactite", "medical-grade-paper", "grid-lacquer", "non-tearable-paper"]
  }
];

/* ---------- PRODUCTS (16) ---------- */
const PRODUCTS = [
  {
    slug: "glassine-paper",
    image: "/assets/products/glassine-paper.webp",
    name: "Glassine Paper",
    aka: "Poly Coated Glassine Paper",
    tagline: "Smooth, super-calendered barrier paper for pharmaceutical packaging.",
    art: "roll-art--cream",
    arm: "Both",
    featured: true,
    construction: "Glassine base + optional PE / VMCH / HSL coating",
    desc: "Glassine is a smooth, super-calendered glossy paper resistant to air, water and grease, an ideal base for pharmaceutical packaging. It is an extremely niche paper, manufactured by only one paper mill in India, and serves as a base that can be further coated using complex polymers.",
    applications: ["ORS sachets", "Strip packing of tablets", "Primary medicine packaging (Saridon, Decdan, Practin)"],
    properties: ["Smooth super-calendered glossy finish", "Resistant to air, water & grease", "Passes stringent quality control", "Multiple coating options for varied protection"],
    variants: ["Pure glassine paper", "Poly-coated glassine", "VMCH / HSL-coated glassine", "Plain or printed reels"],
    coatings: ["PE", "VMCH", "HSL"],
    specs: { finish: "Super-calendered, glossy", coating_type: "PE / VMCH / HSL (optional)", sizes_reels: "Plain or printed reels" },
    certs: ["FSC", "FDA"],
    industries: ["pharmaceutical"],
    cats: { construction: "single", coating: "specialty", fn: ["barrier", "printable"] }
  },
  {
    slug: "mg-poster-paper",
    image: "/assets/products/mg-poster-paper.webp",
    name: "MG Poster Paper",
    aka: "Machine Glazed / Sandwich Paper",
    tagline: "Glossy, high-strength poly-coated paper, a best-seller for primary packaging.",
    art: "roll-art--kraft",
    arm: "Manufactured",
    featured: true,
    construction: "Poster paper + LDPE coating",
    desc: "MG Poster Paper, Machine Glazed Poster Paper, known overseas as poly coated poster paper or 'Sandwich Paper', is one of our best-selling and most sought-after products for primary packaging. Coated with a layer of LDPE during production, it has an extremely glossy appearance, a smooth exterior, high tensile strength and good stiffness. It is an affordable alternative to chromo paper.",
    applications: ["Heat-sealable wrapping", "Pouches", "Inner lining in carton boxes", "Food item packaging", "Apparel & glass wrapping", "Sugar & salt packaging", "Band-aid packaging", "Glove pouches"],
    properties: ["High tensile strength", "Stiff construction", "Glossy appearance", "Smooth exterior finish", "Affordable alternative to chromo"],
    variants: ["Coated", "Uncoated", "Custom specifications"],
    coatings: ["LDPE"],
    specs: { coating_type: "LDPE", finish: "Glossy, machine glazed" },
    certs: [],
    industries: ["food-beverage", "fmcg"],
    cats: { construction: "single", coating: "pe", fn: ["heatseal", "printable"] }
  },
  {
    slug: "chromo-paper",
    image: "/assets/products/chromo-paper.webp",
    name: "Chromo Paper",
    aka: "Poly Coated Chromo Paper",
    tagline: "Water-resistant, high-gloss coated paper built for premium print.",
    art: "roll-art--cream",
    arm: "Manufactured",
    featured: true,
    construction: "Chromo base + inorganic coating + extrusion polymer",
    desc: "Poly coated chromo paper is a highly water-resistant and durable product. It is coated with an inorganic compound that adds ink absorbency, surface gloss and high smoothness. Polymers are applied through extrusion coating lamination, giving the paper additional strength, texture and durability.",
    applications: ["Tobacco sachets", "Magazine paper", "Labels", "Green tea packaging", "Gutka & pan masala packaging"],
    properties: ["Water-resistant", "Extended shelf life", "Excellent for printing", "High ink absorbency", "Gloss finish & smooth texture", "Enhanced strength & durability"],
    variants: ["C1S (one side coated)", "C2S (two sides coated)"],
    coatings: ["Inorganic coat", "Extrusion polymer"],
    specs: { coating_type: "Inorganic + extrusion polymer", finish: "High gloss" },
    certs: [],
    industries: ["fmcg"],
    cats: { construction: "single", coating: "pe", fn: ["printable", "barrier"] }
  },
  {
    slug: "cupstock-paper",
    image: "/assets/products/cupstock-paper.webp",
    name: "Cupstock Paper",
    aka: "PE Coated Cupstock",
    tagline: "Food-safe paper for hot & cold cups, bowls and food service.",
    art: "roll-art--kraft",
    arm: "Both",
    featured: true,
    construction: "2, 3 ply base + PE / PLA / water-based coating",
    desc: "Cupstock paper is a food-safe paper suitable for both hot and cold food and beverages. The base consists of 2, 3 plies that prevent liquid penetration into inner layers, and coatings provide effective protection against light, oxygen, humidity, grease and heat.",
    applications: ["Paper cups", "Noodle & soup bowls", "Food wrappers", "Grocery bags", "Tray mats & meal boxes", "Fast-food containers", "Dry food trays", "Dairy product packaging"],
    properties: ["High hygiene standards", "Low heat transfer", "Liquid-tight when coated", "Moisture & water resistant", "Good sealing properties", "Sustainable & renewable"],
    variants: ["Bleached / unbleached", "Single-sided PE", "Double-sided PE"],
    coatings: ["PE (one/both sides)", "Polylactic acid (PLA)", "Water-based"],
    specs: { coating_type: "PE / PLA / water-based", mechanical: "Scott Bond support", finish: "Food-grade" },
    certs: ["Food-safe"],
    industries: ["food-beverage"],
    cats: { construction: "board", coating: "pe", fn: ["barrier", "heatseal"] }
  },
  {
    slug: "3-ply-paper",
    image: "/assets/products/3-ply-paper.webp",
    name: "3 Ply Paper",
    aka: "Paper + Polymer + Aluminium Foil",
    tagline: "Lightweight, leak-proof foil laminate for maximum freshness.",
    art: "roll-art",
    arm: "Manufactured",
    featured: true,
    construction: "Paper + Polymer + Aluminium Foil",
    desc: "3 Ply Paper, composed of Paper, Polymer and Aluminium Foil, is renowned for sustainability and its superior ability to maintain freshness. It is lightweight, durable, recyclable and leak-proof, effectively blocking water, moisture, air and light.",
    applications: ["Foil bags", "Green tea sachets", "Meat packaging", "Freshness-critical products"],
    properties: ["Excellent thermal conductivity", "Purity & neutrality", "Grease resistance", "Strong texture for varied designs", "Protects against temperature, air, light & moisture"],
    variants: ["Custom laminate structures"],
    coatings: ["Polymer", "Aluminium foil"],
    specs: { construction: "Paper + PE + Foil" },
    certs: [],
    industries: ["pharmaceutical", "food-beverage"],
    cats: { construction: "3ply", coating: "foil", fn: ["barrier"] }
  },
  {
    slug: "4-ply-paper",
    image: "/assets/products/4-ply-paper.webp",
    name: "4 Ply Paper",
    aka: "Paper + PE + Foil + PE",
    tagline: "An extra polymer layer for the toughest pharma & pan-masala barriers.",
    art: "roll-art--kraft",
    arm: "Manufactured",
    featured: true,
    construction: "Paper + PE + Aluminium Foil + PE",
    desc: "Enhancing the versatility of 3 Ply Paper, an extra polymer layer creates 4 Ply Paper, a material highly valued in the pharmaceutical industry for packaging tablet strips and ORS powders. It preserves formulation effectiveness by protecting against moisture and harmful elements while maintaining potency over time.",
    applications: ["Pharmaceutical tablet strips", "ORS powders (e.g. Electral)", "Pan masala packaging", "Moisture-sensitive food & medicine"],
    properties: ["Blocks moisture effectively", "Maintains product freshness", "Protects against extreme temperatures", "Preserves formulation potency"],
    variants: ["Glassine 4 Ply", "Chromo 4 Ply", "Kraft 4 Ply"],
    coatings: ["PE", "Aluminium foil"],
    specs: { construction: "Paper + PE + Foil + PE" },
    certs: [],
    industries: ["pharmaceutical"],
    cats: { construction: "4ply", coating: "foil", fn: ["barrier"] }
  },
  {
    slug: "mg-kraft",
    image: "/assets/products/mg-kraft.webp",
    name: "MG Kraft Paper",
    aka: "Machine Glazed Kraft",
    tagline: "High-strength, eco-friendly kraft with a glossy machine-glazed top.",
    art: "roll-art--kraft",
    arm: "Both",
    featured: true,
    construction: "Kraft base + optional polymer coating",
    desc: "MG Kraft paper is a machine-glazed coated kraft paper that stands out for high tensile strength owing to a greater paper density. It has a natural brown appearance with a high-gloss finish on the top side and is eco-friendly. It can be further coated with polymer layers for enhanced performance.",
    applications: ["Food packaging", "Paper bags", "Envelopes", "Box manufacturing"],
    properties: ["High tensile strength", "Machine-glazed finish", "Natural brown colour & texture", "High MG gloss on top surface", "Strong bursting factor (BF)", "Notable tearing & tensile strength"],
    variants: ["Uncoated", "Polymer coated"],
    coatings: ["Optional polymer"],
    specs: { strength: "Measured by Bursting Factor (BF)", finish: "Natural brown, MG gloss top" },
    certs: [],
    industries: ["food-beverage", "fmcg"],
    cats: { construction: "single", coating: "uncoated", fn: ["printable"] }
  },
  {
    slug: "mf-craft-paper",
    image: "/assets/products/mg-kraft.webp",
    name: "MF Craft Paper",
    aka: "Machine Finished",
    tagline: "Cost-efficient kraft with rough machine-finished texture on both sides.",
    art: "roll-art--kraft",
    arm: "Distributed",
    featured: false,
    construction: "Machine-finished kraft paper",
    desc: "MF Craft Paper is a machine-finished kraft grade with high tensile strength at a lower cost than MG Kraft. It is rough on both sides for better adhesion and is available across BF options from as low as 12.",
    applications: ["Food packaging", "Paper bags", "Envelopes", "Box manufacturing"],
    properties: ["Rough finish on both sides", "Better adhesion", "Natural brown, rose gold and gold shades", "Low to high BF range", "Relatively cheaper than MG"],
    variants: ["Uncoated", "Polymer coated", "Printed"],
    coatings: ["Uncoated", "Polymer coated"],
    specs: { bf: "12-35", finish: "MF, rough both sides", colours: "Natural brown, gold, rose gold" },
    certs: [],
    industries: ["food-beverage", "fmcg"],
    cats: { construction: "single", coating: "uncoated", fn: ["printable"] }
  },
  {
    slug: "folding-box-board",
    image: "/assets/products/folding-box-board.webp",
    name: "Folding Box Board",
    aka: "FBB",
    tagline: "Low-density, high-stiffness board with a superb print surface.",
    art: "roll-art--cream",
    arm: "Distributed",
    featured: false,
    construction: "Chemical pulp / mechanical pulp / chemical pulp layers",
    desc: "Folding Box Board is a multi-layer board with mechanical pulp between chemical pulp layers. It has low density, high stiffness, a bleached surface, a yellowish centre and a bleached inner layer, giving cartons thickness, brightness and reliable print performance.",
    applications: ["Health and beauty", "Frozen foods", "Confectionery", "Pharma cartons", "Cigarette packing"],
    properties: ["Low density", "High stiffness", "Smooth surface for print and foil stamping", "High thickness and brightness", "Eco-friendly"],
    variants: ["FBB only", "FBB + PE", "FBB + PE + aluminium foil", "Sheets and rolls"],
    coatings: ["PE", "Aluminium foil"],
    specs: { structure: "Bleached surface / yellowish centre / bleached inner", finish: "Natural shade, white shade" },
    certs: [],
    industries: ["pharmaceutical", "fmcg", "food-beverage"],
    cats: { construction: "board", coating: "uncoated", fn: ["printable"] }
  },
  {
    slug: "duplex-board",
    image: "/assets/products/duplex-board.webp",
    name: "Duplex Board",
    aka: "Grey Back / White Back",
    tagline: "Rigid, anti-curl coated board with a bright, print-ready face.",
    art: "roll-art--cream",
    arm: "Distributed",
    featured: false,
    construction: "Two-ply board, coated one side",
    desc: "Duplex board is a form of cardboard with a single-sided grey or white colour, made up of two plies. It carries a shiny coated finish on one side, making it superior for printing, and comes in High Weight Coating and Low Weight Coating variants depending on usage.",
    applications: ["Packaging", "Food industry (food-grade)", "Pharmaceutical", "General retail cartons"],
    properties: ["Water-resistant coated exterior", "Tough yet lightweight, bright white", "Rigid, stiff multi-layer build", "Smooth finish for all print types", "Anti-curl property", "Moisture resistant with quality shine"],
    variants: ["HWC", "LWC", "Grey back", "White back", "Single-side PE coated"],
    coatings: ["Single-side coat"],
    specs: { variants: "HWC / LWC", finish: "Grey back or white back" },
    certs: ["Food-grade"],
    industries: ["fmcg", "pharmaceutical", "food-beverage"],
    cats: { construction: "board", coating: "uncoated", fn: ["printable"] }
  },
  {
    slug: "non-tearable-paper",
    image: "/assets/products/non-tearable-paper.webp",
    name: "Non-Woven / Non-Tearable Paper",
    aka: "Special Coated/Uncoated Paper",
    tagline: "Synthetic, breathable, tear-proof, the strength of paper, film and fabric.",
    art: "roll-art",
    arm: "Distributed",
    featured: false,
    construction: "High-density spun-bound polyethylene fibres",
    desc: "Non-Woven / Non-Tearable Paper is lightweight, breathable and resistant to water, wear and tear. Manufactured from high-density spun-bound polyethylene fibres and completely synthetic, it combines the performance of paper, film and fabric, and is also sealable.",
    applications: ["Medical & pharmaceutical packaging", "Industrial protective apparel", "Building protection during construction", "Postal envelopes (Priority/Express)", "Lab & pharma sterilization"],
    properties: ["Lightweight & breathable", "Water, wear & tear resistant", "Bacterial penetration resistant", "Dimensionally stable when printed or coated", "Withstands gamma and ethylene-oxide sterilization"],
    variants: ["Coated", "Uncoated", "Printed", "Roll or sheet"],
    coatings: ["Optional finishing"],
    specs: { material: "Spun-bond polyethylene", gsm: "65-100" },
    certs: [],
    industries: ["medical-surgical", "pharmaceutical"],
    cats: { construction: "single", coating: "specialty", fn: ["sterilizable", "barrier"] }
  },
  {
    slug: "pe-coated-stiffener-paper",
    image: "/assets/products/pe-coated-stiffener-paper.webp",
    name: "PE Stiffener Paper",
    aka: "PE Coated Stiffener",
    tagline: "Rigid PE-coated stiffener for shape, support and moisture protection.",
    art: "roll-art--kraft",
    arm: "Manufactured",
    featured: false,
    construction: "Stiffener base + polyethylene coating",
    desc: "PE Stiffener Paper is used in soap packaging, where the PE coating prevents the paper from becoming brittle on contact with soap. It is also used for air freshener packaging where stiffness, texture and scent compatibility matter.",
    applications: ["Soap industry", "Air freshener industry"],
    properties: ["Leak resistant", "Rigid and supportive", "Moisture and grease barrier", "Good texture and scent"],
    variants: ["PE coated stiffener", "Plain stiffener", "Roll and sheet"],
    coatings: ["Polyethylene"],
    specs: { gsm: "100-200", coating_type: "PE" },
    certs: [],
    industries: ["food-beverage", "fmcg"],
    cats: { construction: "single", coating: "pe", fn: ["barrier"] }
  },
  {
    slug: "greaseproof-paper",
    image: "/assets/products/greaseproof-paper.webp",
    name: "Greaseproof Paper",
    aka: "Oil and Grease Resistant",
    tagline: "Oil-resistant cellulose paper for butter wraps and food packaging.",
    art: "roll-art--cream",
    arm: "Both",
    featured: false,
    construction: "Cellulose-based oil and grease resistant paper",
    desc: "Greaseproof paper, often known as butter paper or OGR, is a smooth cellulose-based paper with low water absorption. It supports multicolour printing and is primarily used to prevent oil penetration in food packaging.",
    applications: ["Packing butter and margarine", "Wrapping food items"],
    properties: ["Prevents oil penetration", "Retains moisture", "Smooth texture", "Low water absorption", "Supports multicolour printing"],
    variants: ["Plain", "Printed", "Coated", "Uncoated", "Roll and sheet"],
    coatings: ["Coated", "Uncoated"],
    specs: { gsm: "32-150" },
    certs: ["Food-safe"],
    industries: ["food-beverage"],
    cats: { construction: "single", coating: "uncoated", fn: ["barrier"] }
  },
  {
    slug: "paper-lid",
    image: "/assets/products/paper-lid.webp",
    name: "Paper Lid",
    aka: "Paper Lid for Aluminium Foil Containers",
    tagline: "Multi-GSM paper lids for hot food packed in aluminium foil containers.",
    art: "roll-art--cream",
    arm: "Manufactured",
    featured: false,
    construction: "High-GSM paperboard lid",
    desc: "Paper Lid is a high-quality multi-GSM lid for aluminium foil containers. It resists hot liquids such as curries and dals, stays firm during use, and helps prevent sogginess and leakage.",
    applications: ["Food packaging"],
    properties: ["Great edge wick", "No leakage", "Glossy or matte finish", "Strong burst factor"],
    variants: ["One-side P coated", "Two-side P coated", "Uncoated"],
    coatings: ["One-side P coated", "Two-side P coated", "Uncoated"],
    specs: { gsm: "230-550", finish: "Glossy / matte" },
    certs: ["Food-safe"],
    industries: ["food-beverage"],
    cats: { construction: "board", coating: "pe", fn: ["barrier"] }
  },
  {
    slug: "anti-skid-paper",
    image: "/assets/products/anti-skid-paper.webp",
    name: "Anti-Skid Paper",
    aka: "Pallet Stabilization Paper",
    tagline: "Non-slip paper that locks pallet layers and trays in place.",
    art: "roll-art--kraft",
    arm: "Distributed",
    featured: false,
    construction: "Recycled anti-skid paper",
    desc: "Anti-Skid Paper creates friction on contact with cartons, trays and pallet surfaces. It helps stop movement even by hand and is available with one-side or two-side anti-skid treatment.",
    applications: ["Pallet packing", "Food trays"],
    properties: ["Anti-skid", "Recycled", "Multiple GSMs", "Any colour"],
    variants: ["One-side anti-skid", "Two-side anti-skid"],
    coatings: ["Anti-skid coating"],
    specs: { gsm: "40-400" },
    certs: [],
    industries: ["food-beverage", "fmcg"],
    cats: { construction: "single", coating: "specialty", fn: ["barrier"] }
  },
  {
    slug: "liquid-packaging-board",
    image: "/assets/products/liquid-packaging-board.webp",
    name: "Liquid Packaging Board",
    aka: "LPB",
    tagline: "Multi-layer board for gable-top and aseptic liquid packaging.",
    art: "roll-art--cream",
    arm: "Distributed",
    featured: false,
    construction: "4, 5, 6 or 7 ply liquid packaging board",
    desc: "Liquid Packaging Board is a multi-layer board used for gable-top and aseptic structures. Its 4, 5, 6 and 7 ply formats are used to pack water, juice, milk and alcohol.",
    applications: ["Water packaging", "Juice packaging", "Milk packaging", "Alcohol packaging"],
    properties: ["Multi-layer structure", "Suitable for gable-top packs", "Suitable for aseptic structures", "Strong liquid-packaging stiffness"],
    variants: ["LPB 4-ply", "LPB 5-ply", "LPB 6-ply", "LPB 7-ply"],
    coatings: ["Liquid packaging coating"],
    specs: { gsm: "200-450" },
    certs: ["Food-safe"],
    industries: ["food-beverage"],
    cats: { construction: "board", coating: "pe", fn: ["barrier"] }
  },
  {
    slug: "butcher-paper",
    image: "/assets/products/butcher-paper.webp",
    name: "Butcher Paper",
    aka: "Meat Wrapping Paper",
    tagline: "Strong kraft-style wrapping paper for meat packaging.",
    art: "roll-art--kraft",
    arm: "Distributed",
    featured: false,
    construction: "Kraft paper for meat wrapping",
    desc: "Butcher Paper is a strong kraft-style paper used for packaging meat. It is similar in feel to newsprint but is made for wrapping performance, with strength and meat-packaging utility as the priority.",
    applications: ["Meat packaging", "Butcher wrapping", "Food wrapping"],
    properties: ["Strong wrapping performance", "Kraft-based structure", "Neutral pH options", "Natural or bleached shades"],
    variants: ["Natural", "Bleached", "Printed", "Roll and sheet"],
    coatings: ["Uncoated", "Waxed / treated options"],
    specs: { finish: "Newsprint-like wrapping finish" },
    certs: ["Food-safe"],
    industries: ["food-beverage"],
    cats: { construction: "single", coating: "uncoated", fn: ["barrier"] }
  },
  {
    slug: "medical-grade-paper",
    image: "/assets/products/medical-grade-paper.webp",
    name: "Medical Grade Paper",
    aka: "Medical Device Packaging Paper",
    tagline: "Virgin wood-based paper for sterile medical device packaging.",
    art: "roll-art",
    arm: "Both",
    featured: false,
    construction: "Virgin wood-based medical paper",
    desc: "Medical Grade Paper is a high-quality virgin wood-based paper for medical device packing. It can be laminated directly with CPP, offers very high strength, and is designed for sterile barrier packaging requirements.",
    applications: ["Medical device packaging", "Medical pouches", "Pharma"],
    properties: ["Seals with CPP", "Microbial barrier performance", "Low linting and clean opening", "High tensile and burst strength", "Sterilization compatible"],
    variants: ["Imported medical grade", "Indian medical grade", "Stock lot"],
    coatings: ["Coated", "Uncoated"],
    specs: { gsm: "40-100" },
    certs: [],
    industries: ["medical-surgical", "pharmaceutical"],
    cats: { construction: "single", coating: "specialty", fn: ["sterilizable", "heatseal", "barrier"] }
  },
  {
    slug: "butter-packaging",
    image: "/assets/products/butter-packaging.webp",
    name: "Butter Packaging",
    aka: "Grease Proof + PE Foil",
    tagline: "Greaseproof and foil laminate for butter, cheese and oily foods.",
    art: "roll-art--cream",
    arm: "Manufactured",
    featured: false,
    construction: "Grease proof + PE + foil",
    desc: "Butter Packaging uses a greaseproof + PE foil structure where the greaseproof layer contacts butter directly and the foil side remains printable. It is engineered to prevent grease leakage while supporting attractive pack printing.",
    applications: ["Butter packaging", "Cheese packaging", "Greasy foods"],
    properties: ["Grease resistant", "Printable on paper or foil side", "No leakage", "Direct food-contact greaseproof layer"],
    variants: ["Grease proof 3-ply", "Foil wash", "PFAS free", "FSC"],
    coatings: ["PE", "Aluminium foil"],
    specs: { gsm: "65-150", construction: "Grease proof + PE + foil" },
    certs: ["FSC"],
    industries: ["food-beverage"],
    cats: { construction: "3ply", coating: "foil", fn: ["barrier", "printable"] }
  },
  {
    slug: "maplitho-paper",
    image: "/assets/products/maplitho-paper.webp",
    name: "Maplitho Paper",
    aka: "Surface-Sized Wood-Free Paper",
    tagline: "Eco-friendly, wood-free printing & writing paper.",
    art: "roll-art--cream",
    arm: "Distributed",
    featured: false,
    construction: "Wood-free, surface-sized",
    desc: "Maplitho, meaning 'surface size-paper', is an eco-friendly, wood-free paper distributed by KP Packaging. The nature of the paper used for printing plays an important role in the quality of the final printed product, and Maplitho enables crisp embossing on both sides.",
    applications: ["Computer stationery", "Bills, invoices & cashbooks", "Leaflets & mailers", "Calendars & writing pads", "Label printing", "Braille printing", "Laser / inkjet / photocopy"],
    properties: ["Eco-friendly & wood-free", "Embossing on both sides", "Available in multiple sizes", "Available in two shades", "Recyclable"],
    variants: ["Two shades", "Multiple sizes", "Surface sized", "Coated", "Uncoated", "Roll and sheet"],
    coatings: ["Surface-sized", "Coated", "Uncoated"],
    specs: { gsm: "50-100", type: "Wood-free, surface-sized", shades: "Two" },
    certs: [],
    industries: ["fmcg"],
    cats: { construction: "single", coating: "uncoated", fn: ["printable"] }
  },
  {
    slug: "tissue-paper",
    image: "/assets/products/tissue-paper.webp",
    name: "Tissue Paper",
    aka: "Facial, Toilet, Towel, Napkin",
    tagline: "Soft, absorbent, hygienic tissue from recycled pulp.",
    art: "roll-art--cream",
    arm: "Distributed",
    featured: false,
    construction: "Recycled paper pulp",
    desc: "Tissue paper is a lightweight paper made from recycled pulp. It is hygienic and versatile, covering facial tissue, napkin, towel and bathroom tissue formats, and can be customized for manufacturer branding.",
    applications: ["Facial tissues", "Paper napkins", "Paper towels", "Bathroom & toilet tissue"],
    properties: ["Soft, absorbent and disposable", "Hygienic", "Customizable", "Versatile tissue formats", "Made from recycled pulp"],
    variants: ["Facial", "Napkin", "Towel", "Bathroom / toilet"],
    coatings: ["Uncoated"],
    specs: { gsm: "15-52", material: "Recycled paper pulp" },
    certs: [],
    industries: ["food-beverage"],
    cats: { construction: "single", coating: "uncoated", fn: [] }
  },
  {
    slug: "bactite",
    image: "/assets/products/bactite.webp",
    name: "Bactide Paper",
    aka: "Medical Sterilization Paper",
    tagline: "Steam-sterilizable, bacterial-barrier paper for medical packaging.",
    art: "roll-art",
    arm: "Manufactured",
    featured: false,
    construction: "Medical sterilization paper",
    desc: "Hygienically produced and free from optical brighteners, Bactide paper is developed to fulfil special requirements of heat sealability and is suitable for steam sterilization, giving it a colour indication. Its excellent fluid-repellent quality and bacterial-growth barrier make it ideal for packaging medical products, mainly hand gloves.",
    applications: ["Medical hand glove sterilization"],
    properties: ["High dry and wet strength", "Lint free", "Colour indication for steam sterilization", "Free from optical brighteners", "Fluid repellent", "Bacterial barrier"],
    variants: ["Plain", "Printed", "Heat sealable", "Coated", "Uncoated"],
    coatings: ["Heat-sealable", "Coated", "Uncoated"],
    specs: { gsm: "60-80", feature: "Steam-sterilizable with colour indication" },
    certs: [],
    industries: ["medical-surgical"],
    cats: { construction: "single", coating: "specialty", fn: ["sterilizable", "heatseal"] }
  },
  {
    slug: "grid-lacquer",
    image: "/assets/products/grid-lacquer.webp",
    name: "Grid Coated Paper",
    aka: "Grid Lacquer",
    tagline: "Breathable grid-coated medical paper for heat-seal sterile packs.",
    art: "roll-art",
    arm: "Manufactured",
    featured: false,
    construction: "Paper + grid coating",
    desc: "Grid Coated Paper is medical grade packaging paper with heat-sealable lacquer applied in a grid pattern. It is sterilization-compatible, supports fibre-free peeling and stays breathable because gases can pass through the open grid lines.",
    applications: ["Sterile medical packing", "Heat-seal pouches", "Automatic online wrapping", "Surgical glove packing", "Syringe and catheter covers", "Band-aid wrappers"],
    properties: ["Heat sealability", "Fiber-free peeling", "Breathable grid pattern", "High strength", "Virgin medical grade wood pulp", "5-10 GSM coating weight"],
    variants: ["60+5", "60+10", "Imported", "Indian", "Stock lot"],
    coatings: ["Grid lacquer", "Heat-sealable lacquer"],
    specs: { construction: "Paper + grid coating", gsm: "60-80" },
    certs: [],
    industries: ["medical-surgical"],
    cats: { construction: "single", coating: "specialty", fn: ["sterilizable", "heatseal"] }
  }
];

/* ---------- Catalogue filter definitions ---------- */
const FILTERS = {
  industry: [
    { key: "pharmaceutical", label: "Pharmaceutical" },
    { key: "food-beverage", label: "Food & Beverage" },
    { key: "fmcg", label: "FMCG & Retail" },
    { key: "medical-surgical", label: "Medical & Surgical" }
  ],
  construction: [
    { key: "single", label: "Single-ply" },
    { key: "3ply", label: "3-Ply" },
    { key: "4ply", label: "4-Ply" },
    { key: "board", label: "Board" }
  ],
  coating: [
    { key: "pe", label: "PE Coated" },
    { key: "foil", label: "Foil Laminate" },
    { key: "specialty", label: "Specialty Coated" },
    { key: "uncoated", label: "Uncoated" }
  ],
  fn: [
    { key: "barrier", label: "Moisture / Grease Barrier" },
    { key: "heatseal", label: "Heat-Sealable" },
    { key: "sterilizable", label: "Sterilizable" },
    { key: "printable", label: "Print-Ready" }
  ]
};

/* ---------- Node (build-time) export; no-op in the browser ---------- */
if (typeof module !== "undefined" && module.exports) {
  module.exports = { COMPANY, CAPABILITIES, INDUSTRIES, INFRASTRUCTURE, PRODUCTS, FILTERS };
}
